import pandas as pd
from pyexcel_ods import save_data
from collections import OrderedDict


def save_ods_from_excel(excel_file, target_ods_file):
    # First read into dataframe
    df = pd.read_excel(excel_file)
    # Change everything to string since we're just writing
    df = df.astype(str)
    # Initiliaze data to be written as an empty list, as pyods needs a list to write
    whole_data_list = []
    # Initiliaze the empty dict() for the data
    d = OrderedDict()
    # Write the columns first to be the first entries
    whole_data_list.append(list(df.columns))
    # loop through data frame and update the data list
    for index, row in df.iterrows():
        whole_data_list.append(list(row.values))
    # Populate dict() with updated data list
    d.update({"Moved sheet": whole_data_list})
    # Finally call save_data() from pyods to store the ods file
    save_data(target_ods_file, d)


def main(r_by_i):

    print(len(r_by_i))
    speadsheet = pd.DataFrame(r_by_i)
    speadsheet.to_excel('test.xlsx', sheet_name='radiance', index=False)
    return None


masked = -999

reflectance_by_image = [[{'Img': '20200216T135345',
                          'Point': 1,
                          'Lon': -58.14970549294257,
                          'Lat': -2.9856994542458475,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200216T135345',
                          'Point': 2,
                          'Lon': -58.90452547113001,
                          'Lat': -3.2841064996074416,
                          'Rad': [-0.01853694,
                                  -0.013849303,
                                  0.004828036,
                                  0.029529706,
                                  0.043244734,
                                  0.083712265,
                                  0.11280863,
                                  0.12397839,
                                  0.12610249,
                                  0.12782373,
                                  0.11899777,
                                  0.070143744,
                                  0.07380597,
                                  0.04839015,
                                  0.042658776,
                                  0.02198553]},
                         {'Img': '20200216T135345',
                          'Point': 3,
                          'Lon': -58.9607318793036,
                          'Lat': -3.606902502063587,
                          'Rad': [0.011639759,
                                  0.011163667,
                                  0.020941809,
                                  0.031525627,
                                  0.040168464,
                                  0.06655477,
                                  0.08466445,
                                  0.09105502,
                                  0.091897324,
                                  0.09261148,
                                  0.0982513,
                                  0.08530535,
                                  0.0903409,
                                  0.06670125,
                                  0.059981093,
                                  0.013818786]},
                         {'Img': '20200216T135345',
                          'Point': 4,
                          'Lon': -60.078983746677025,
                          'Lat': -3.317089302133001,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200216T135345',
                          'Point': 5,
                          'Lon': -61.31994532823368,
                          'Lat': -5.8397227764153525,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200216T135345',
                          'Point': 6,
                          'Lon': -60.5362264724846,
                          'Lat': -6.9713248552570795,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200216T135345',
                          'Point': 7,
                          'Lon': -64.26934904609394,
                          'Lat': -5.587853822242022,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200216T135345',
                          'Point': 8,
                          'Lon': -64.4411701650366,
                          'Lat': -3.4793143118916987,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200216T135345',
                          'Point': 9,
                          'Lon': -68.40596888519887,
                          'Lat': -3.3614512187222148,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200216T135345',
                          'Point': 10,
                          'Lon': -65.29590076652481,
                          'Lat': -10.231527957597688,
                          'Rad': [-0.055049285,
                                  -0.050965905,
                                  -0.029560223,
                                  -0.0029724985,
                                  0.015594959,
                                  0.06655477,
                                  0.10440384,
                                  0.12059085,
                                  0.12383191,
                                  0.12569965,
                                  0.14247261,
                                  0.17089145,
                                  0.15494247,
                                  0.14999847,
                                  0.14325999,
                                  0.09253822]}],
                        [{'Img': '20200216T135345',
                          'Point': 1,
                          'Lon': -58.14970549294257,
                          'Lat': -2.9856994542458475,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200216T135345',
                          'Point': 2,
                          'Lon': -58.90452547113001,
                          'Lat': -3.2841064996074416,
                          'Rad': [-0.018646806,
                                  -0.013959169,
                                  0.0047547817,
                                  0.029456466,
                                  0.04317148,
                                  0.08360241,
                                  0.11269875,
                                  0.12388684,
                                  0.12599261,
                                  0.12771387,
                                  0.118906215,
                                  0.07010712,
                                  0.0738426,
                                  0.048426777,
                                  0.04267709,
                                  0.022003844]},
                         {'Img': '20200216T135345',
                          'Point': 3,
                          'Lon': -58.9607318793036,
                          'Lat': -3.606902502063587,
                          'Rad': [0.011401713,
                                  0.010962248,
                                  0.020831943,
                                  0.031507313,
                                  0.04020509,
                                  0.06666462,
                                  0.084829256,
                                  0.091256455,
                                  0.09208046,
                                  0.09281288,
                                  0.0984527,
                                  0.08552508,
                                  0.09046908,
                                  0.066866055,
                                  0.06014587,
                                  0.013946965]},
                         {'Img': '20200216T135345',
                          'Point': 4,
                          'Lon': -60.078983746677025,
                          'Lat': -3.317089302133001,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200216T135345',
                          'Point': 5,
                          'Lon': -61.31994532823368,
                          'Lat': -5.8397227764153525,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200216T135345',
                          'Point': 6,
                          'Lon': -60.5362264724846,
                          'Lat': -6.9713248552570795,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200216T135345',
                          'Point': 7,
                          'Lon': -64.26934904609394,
                          'Lat': -5.587853822242022,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200216T135345',
                          'Point': 8,
                          'Lon': -64.4411701650366,
                          'Lat': -3.4793143118916987,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200216T135345',
                          'Point': 9,
                          'Lon': -68.40596888519887,
                          'Lat': -3.3614512187222148,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200216T135345',
                          'Point': 10,
                          'Lon': -65.29590076652481,
                          'Lat': -10.231527957597688,
                          'Rad': [-0.053913996,
                                  -0.049867243,
                                  -0.028626367,
                                  -0.0022034347,
                                  0.016309097,
                                  0.06706749,
                                  0.10502641,
                                  0.12108524,
                                  0.124308005,
                                  0.12613912,
                                  0.14287545,
                                  0.17127599,
                                  0.15551011,
                                  0.15062104,
                                  0.14388256,
                                  0.093252346]}],
                        [{'Img': '20200217T132735',
                          'Point': 1,
                          'Lon': -58.14970549294257,
                          'Lat': -2.9856994542458475,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200217T132735',
                          'Point': 2,
                          'Lon': -58.90452547113001,
                          'Lat': -3.2841064996074416,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200217T132735',
                          'Point': 3,
                          'Lon': -58.9607318793036,
                          'Lat': -3.606902502063587,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200217T132735',
                          'Point': 4,
                          'Lon': -60.078983746677025,
                          'Lat': -3.317089302133001,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200217T132735',
                          'Point': 5,
                          'Lon': -61.31994532823368,
                          'Lat': -5.8397227764153525,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200217T132735',
                          'Point': 6,
                          'Lon': -60.5362264724846,
                          'Lat': -6.9713248552570795,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200217T132735',
                          'Point': 7,
                          'Lon': -64.26934904609394,
                          'Lat': -5.587853822242022,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200217T132735',
                          'Point': 8,
                          'Lon': -64.4411701650366,
                          'Lat': -3.4793143118916987,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200217T132735',
                          'Point': 9,
                          'Lon': -68.40596888519887,
                          'Lat': -3.3614512187222148,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200217T132735',
                          'Point': 10,
                          'Lon': -65.29590076652481,
                          'Lat': -10.231527957597688,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]}],
                        [{'Img': '20200220T135001',
                          'Point': 1,
                          'Lon': -58.14970549294257,
                          'Lat': -2.9856994542458475,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 2,
                          'Lon': -58.90452547113001,
                          'Lat': -3.2841064996074416,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 3,
                          'Lon': -58.9607318793036,
                          'Lat': -3.606902502063587,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 4,
                          'Lon': -60.078983746677025,
                          'Lat': -3.317089302133001,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 5,
                          'Lon': -61.31994532823368,
                          'Lat': -5.8397227764153525,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 6,
                          'Lon': -60.5362264724846,
                          'Lat': -6.9713248552570795,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 7,
                          'Lon': -64.26934904609394,
                          'Lat': -5.587853822242022,
                          'Rad': [-0.015021205,
                                  -0.017053738,
                                  -0.044996485,
                                  -0.028168589,
                                  -0.023114726,
                                  0.013690606,
                                  0.043739125,
                                  0.061061427,
                                  0.064980015,
                                  0.06734215,
                                  0.06997894,
                                  0.024182871,
                                  0.010211498,
                                  6.714463e-05,
                                  -0.0042542815,
                                  -0.015881836]},
                         {'Img': '20200220T135001',
                          'Point': 8,
                          'Lon': -64.4411701650366,
                          'Lat': -3.4793143118916987,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 9,
                          'Lon': -68.40596888519887,
                          'Lat': -3.3614512187222148,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 10,
                          'Lon': -65.29590076652481,
                          'Lat': -10.231527957597688,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]}],
                        [{'Img': '20200220T135001',
                          'Point': 1,
                          'Lon': -58.14970549294257,
                          'Lat': -2.9856994542458475,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 2,
                          'Lon': -58.90452547113001,
                          'Lat': -3.2841064996074416,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 3,
                          'Lon': -58.9607318793036,
                          'Lat': -3.606902502063587,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 4,
                          'Lon': -60.078983746677025,
                          'Lat': -3.317089302133001,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 5,
                          'Lon': -61.31994532823368,
                          'Lat': -5.8397227764153525,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 6,
                          'Lon': -60.5362264724846,
                          'Lat': -6.9713248552570795,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 7,
                          'Lon': -64.26934904609394,
                          'Lat': -5.587853822242022,
                          'Rad': [-0.10260323,
                                  -0.09236732,
                                  -0.06065248,
                                  -0.01677908,
                                  0.005780205,
                                  0.06551103,
                                  0.107077256,
                                  0.13111971,
                                  0.13602711,
                                  0.13899352,
                                  0.14380933,
                                  0.101950124,
                                  0.09645681,
                                  0.06867884,
                                  0.06104313,
                                  0.059724733]},
                         {'Img': '20200220T135001',
                          'Point': 8,
                          'Lon': -64.4411701650366,
                          'Lat': -3.4793143118916987,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 9,
                          'Lon': -68.40596888519887,
                          'Lat': -3.3614512187222148,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200220T135001',
                          'Point': 10,
                          'Lon': -65.29590076652481,
                          'Lat': -10.231527957597688,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]}],
                        [{'Img': '20200221T132350',
                          'Point': 1,
                          'Lon': -58.14970549294257,
                          'Lat': -2.9856994542458475,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 2,
                          'Lon': -58.90452547113001,
                          'Lat': -3.2841064996074416,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 3,
                          'Lon': -58.9607318793036,
                          'Lat': -3.606902502063587,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 4,
                          'Lon': -60.078983746677025,
                          'Lat': -3.317089302133001,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 5,
                          'Lon': -61.31994532823368,
                          'Lat': -5.8397227764153525,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 6,
                          'Lon': -60.5362264724846,
                          'Lat': -6.9713248552570795,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 7,
                          'Lon': -64.26934904609394,
                          'Lat': -5.587853822242022,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 8,
                          'Lon': -64.4411701650366,
                          'Lat': -3.4793143118916987,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 9,
                          'Lon': -68.40596888519887,
                          'Lat': -3.3614512187222148,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 10,
                          'Lon': -65.29590076652481,
                          'Lat': -10.231527957597688,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]}],
                        [{'Img': '20200221T132350',
                          'Point': 1,
                          'Lon': -58.14970549294257,
                          'Lat': -2.9856994542458475,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 2,
                          'Lon': -58.90452547113001,
                          'Lat': -3.2841064996074416,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 3,
                          'Lon': -58.9607318793036,
                          'Lat': -3.606902502063587,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 4,
                          'Lon': -60.078983746677025,
                          'Lat': -3.317089302133001,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 5,
                          'Lon': -61.31994532823368,
                          'Lat': -5.8397227764153525,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 6,
                          'Lon': -60.5362264724846,
                          'Lat': -6.9713248552570795,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 7,
                          'Lon': -64.26934904609394,
                          'Lat': -5.587853822242022,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 8,
                          'Lon': -64.4411701650366,
                          'Lat': -3.4793143118916987,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 9,
                          'Lon': -68.40596888519887,
                          'Lat': -3.3614512187222148,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200221T132350',
                          'Point': 10,
                          'Lon': -65.29590076652481,
                          'Lat': -10.231527957597688,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]}],
                        [{'Img': '20200218T140249',
                          'Point': 1,
                          'Lon': -58.14970549294257,
                          'Lat': -2.9856994542458475,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200218T140249',
                          'Point': 2,
                          'Lon': -58.90452547113001,
                          'Lat': -3.2841064996074416,
                          'Rad': [0.008197278,
                                  0.0069338083,
                                  0.0066408217,
                                  0.008819848,
                                  0.012134165,
                                  0.024988562,
                                  0.033466592,
                                  0.036964014,
                                  0.036890775,
                                  0.037769705,
                                  0.03531602,
                                  0.021747485,
                                  0.022956029,
                                  0.012244031,
                                  0.008984655,
                                  0.023981452]},
                         {'Img': '20200218T140249',
                          'Point': 3,
                          'Lon': -58.9607318793036,
                          'Lat': -3.606902502063587,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200218T140249',
                          'Point': 4,
                          'Lon': -60.078983746677025,
                          'Lat': -3.317089302133001,
                          'Rad': [0.06657307,
                                  0.07019867,
                                  0.07933591,
                                  0.0939848,
                                  0.102957234,
                                  0.13214515,
                                  0.15474106,
                                  0.16393323,
                                  0.16536151,
                                  0.16658835,
                                  0.16129644,
                                  0.11709343,
                                  0.12253182,
                                  0.09594409,
                                  0.08984651,
                                  0.065730765]},
                         {'Img': '20200218T140249',
                          'Point': 5,
                          'Lon': -61.31994532823368,
                          'Lat': -5.8397227764153525,
                          'Rad': [-0.06565142,
                                  -0.057997376,
                                  -0.035383165,
                                  -0.008319348,
                                  0.009918511,
                                  0.062343225,
                                  0.10264595,
                                  0.11709343,
                                  0.11910765,
                                  0.12062748,
                                  0.13183387,
                                  0.10925625,
                                  0.1042207,
                                  0.0804712,
                                  0.072396025,
                                  -0.008557394]},
                         {'Img': '20200218T140249',
                          'Point': 6,
                          'Lon': -60.5362264724846,
                          'Lat': -6.9713248552570795,
                          'Rad': [0.023889884,
                                  0.023047581,
                                  0.024677262,
                                  0.02941984,
                                  0.033448294,
                                  0.04851833,
                                  0.056703404,
                                  0.060310677,
                                  0.06087832,
                                  0.060951576,
                                  0.049507126,
                                  0.021729186,
                                  0.020264298,
                                  0.011145353,
                                  0.008636743,
                                  0.013892025]},
                         {'Img': '20200218T140249',
                          'Point': 7,
                          'Lon': -64.26934904609394,
                          'Lat': -5.587853822242022,
                          'Rad': [-0.010388494,
                                  -0.0009582788,
                                  0.017902166,
                                  0.0436842,
                                  0.057087913,
                                  0.09997253,
                                  0.13093661,
                                  0.14818569,
                                  0.15239723,
                                  0.15472274,
                                  0.15065767,
                                  0.10791956,
                                  0.11013521,
                                  0.0860744,
                                  0.07988526,
                                  0.07223122]},
                         {'Img': '20200218T140249',
                          'Point': 8,
                          'Lon': -64.4411701650366,
                          'Lat': -3.4793143118916987,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200218T140249',
                          'Point': 9,
                          'Lon': -68.40596888519887,
                          'Lat': -3.3614512187222148,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200218T140249',
                          'Point': 10,
                          'Lon': -65.29590076652481,
                          'Lat': -10.231527957597688,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]}],
                        [{'Img': '20200218T140249',
                          'Point': 1,
                          'Lon': -58.14970549294257,
                          'Lat': -2.9856994542458475,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200218T140249',
                          'Point': 2,
                          'Lon': -58.90452547113001,
                          'Lat': -3.2841064996074416,
                          'Rad': [0.007885978,
                                  0.006585896,
                                  0.006256297,
                                  0.008435324,
                                  0.011767939,
                                  0.024732202,
                                  0.033210248,
                                  0.036634415,
                                  0.036561176,
                                  0.037440106,
                                  0.035004735,
                                  0.021472827,
                                  0.022772908,
                                  0.012115851,
                                  0.008874789,
                                  0.023926511]},
                         {'Img': '20200218T140249',
                          'Point': 3,
                          'Lon': -58.9607318793036,
                          'Lat': -3.606902502063587,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200218T140249',
                          'Point': 4,
                          'Lon': -60.078983746677025,
                          'Lat': -3.317089302133001,
                          'Rad': [-0.008117929,
                                  -0.0022217482,
                                  0.012244031,
                                  0.03342998,
                                  0.0451857,
                                  0.08184455,
                                  0.10881679,
                                  0.119785145,
                                  0.12150641,
                                  0.12295298,
                                  0.11745964,
                                  0.06915493,
                                  0.06820278,
                                  0.043446153,
                                  0.037696466,
                                  0.01689504]},
                         {'Img': '20200218T140249',
                          'Point': 5,
                          'Lon': -61.31994532823368,
                          'Lat': -5.8397227764153525,
                          'Rad': [-0.065303504,
                                  -0.05781427,
                                  -0.035547957,
                                  -0.0087405,
                                  0.00929594,
                                  0.0616657,
                                  0.10152899,
                                  0.11581163,
                                  0.11780755,
                                  0.11930905,
                                  0.13042392,
                                  0.108084366,
                                  0.10416578,
                                  0.08039798,
                                  0.07232277,
                                  -0.008758813]},
                         {'Img': '20200218T140249',
                          'Point': 6,
                          'Lon': -60.5362264724846,
                          'Lat': -6.9713248552570795,
                          'Rad': [0.02376172,
                                  0.022937715,
                                  0.024585709,
                                  0.029383227,
                                  0.033448294,
                                  0.04859157,
                                  0.056776628,
                                  0.060347304,
                                  0.06091495,
                                  0.060969874,
                                  0.049507126,
                                  0.021729186,
                                  0.020264298,
                                  0.011145353,
                                  0.008636743,
                                  0.013892025]},
                         {'Img': '20200218T140249',
                          'Point': 7,
                          'Lon': -64.26934904609394,
                          'Lat': -5.587853822242022,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200218T140249',
                          'Point': 8,
                          'Lon': -64.4411701650366,
                          'Lat': -3.4793143118916987,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200218T140249',
                          'Point': 9,
                          'Lon': -68.40596888519887,
                          'Lat': -3.3614512187222148,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200218T140249',
                          'Point': 10,
                          'Lon': -65.29590076652481,
                          'Lat': -10.231527957597688,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]}],
                        [{'Img': '20200219T133638',
                          'Point': 1,
                          'Lon': -58.14970549294257,
                          'Lat': -2.9856994542458475,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 2,
                          'Lon': -58.90452547113001,
                          'Lat': -3.2841064996074416,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 3,
                          'Lon': -58.9607318793036,
                          'Lat': -3.606902502063587,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 4,
                          'Lon': -60.078983746677025,
                          'Lat': -3.317089302133001,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 5,
                          'Lon': -61.31994532823368,
                          'Lat': -5.8397227764153525,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 6,
                          'Lon': -60.5362264724846,
                          'Lat': -6.9713248552570795,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 7,
                          'Lon': -64.26934904609394,
                          'Lat': -5.587853822242022,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 8,
                          'Lon': -64.4411701650366,
                          'Lat': -3.4793143118916987,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 9,
                          'Lon': -68.40596888519887,
                          'Lat': -3.3614512187222148,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 10,
                          'Lon': -65.29590076652481,
                          'Lat': -10.231527957597688,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]}],
                        [{'Img': '20200219T133638',
                          'Point': 1,
                          'Lon': -58.14970549294257,
                          'Lat': -2.9856994542458475,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 2,
                          'Lon': -58.90452547113001,
                          'Lat': -3.2841064996074416,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 3,
                          'Lon': -58.9607318793036,
                          'Lat': -3.606902502063587,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 4,
                          'Lon': -60.078983746677025,
                          'Lat': -3.317089302133001,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 5,
                          'Lon': -61.31994532823368,
                          'Lat': -5.8397227764153525,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 6,
                          'Lon': -60.5362264724846,
                          'Lat': -6.9713248552570795,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 7,
                          'Lon': -64.26934904609394,
                          'Lat': -5.587853822242022,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 8,
                          'Lon': -64.4411701650366,
                          'Lat': -3.4793143118916987,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 9,
                          'Lon': -68.40596888519887,
                          'Lat': -3.3614512187222148,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]},
                         {'Img': '20200219T133638',
                          'Point': 10,
                          'Lon': -65.29590076652481,
                          'Lat': -10.231527957597688,
                          'Rad': [masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked,
                                  masked]}]]

if __name__ == '__main__':
    main(reflectance_by_image)
